name: Benchmark
on:
  workflow_dispatch:
jobs:
  measure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org/
      - uses: cachix/cachix-action@v12
        with:
          name: tylerjl-pub
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run benchmarks
        run: make benchmarks
      - uses: EndBug/add-and-commit@v9
        with:
          add: docs/benchmarks
          message: 'Criterion benchmarks for ${{ github.sha }}'
