name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://cache.nixos.org/
      - uses: cachix/cachix-action@v10
        with:
          name: tylerjl-pub
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build the project
        run: nix build
      - name: Run the executable
        run: ./result/bin/adventofcode --help
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://cache.nixos.org/
      - uses: cachix/cachix-action@v10
        with:
          name: tylerjl-pub
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run the test suite
        run: make test
